apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.odoo.pvc.name}}
  labels:
    app: odoo
spec:
  storageClassName: {{.Values.odoo.pvc.storageClassName}}
  accessModes:
    - {{.Values.odoo.pvc.accessModes}}
  resources:
    requests:
      storage: {{.Values.odoo.pvc.storage}}
