apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.odoo.config.name}}
  labels:
    app: odoo
data:
  HOST: {{.Values.odoo.config.host}}
  USER: {{.Values.odoo.config.user}}
  PASSWORD: {{.Values.odoo.config.password}}

