apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: postgre-pv-volume # Sets PV's name
  labels:
    type: local # Sets PV's type to local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data" # Sets the volume's path
