apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: {{.Values.postgres.pv.name}} # Sets PV's name
  labels:
    type: {{.Values.postgres.pv.type}} # Sets PV's type to local
    app: postgres
spec:
  storageClassName: {{.Values.postgres.pv.storageClassName}}
  capacity:
    storage: {{.Values.postgres.pv.storage}} # Sets PV Volume
  accessModes:
    - {{.Values.postgres.pv.accessMode}}
  hostPath:
    path: {{.Values.postgres.pv.hostPath}} # Sets the volume's path
