apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.postgres.config_map_name}}
  labels:
    app: postgres
data:
  POSTGRES_DB: {{.Values.postgres.postgres_db}}
  POSTGRES_USER: {{.Values.postgres.postgres_user}}
  POSTGRES_PASSWORD: {{.Values.postgres.postgres_pass}}
