apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.postgres.config.name}}
  labels:
    app: postgres
data:
  POSTGRES_DB: {{.Values.postgres.config.db}}
  POSTGRES_USER: {{.Values.postgres.config.user}}
  POSTGRES_PASSWORD: {{.Values.postgres.config.pass}}
